[templates]
log = 'log_oneline'

[template-aliases]
'diff_numstat' = 'diff_numstat(self)'
'diff_numstat(commit)' = '''
commit.diff().stat().files().map(|f|
  separate("\x00",
    "bijjou_template_name\x00diff_numstat",
    "lines_added\x00" ++ label(if(f.lines_added() == 0, "rest", "diff added"), f.lines_added()),
    "lines_removed\x00" ++ label(if(f.lines_removed() == 0, "rest", "diff removed"), f.lines_removed()),
    "status_char\x00" ++ label(
       if(f.status() == "modified", "diff modified",
         if(f.status() == "added", "diff added",
           if(f.status() == "removed", "diff removed",
             if(f.status() == "copied", "diff copied",
               if(f.status() == "renamed", "diff renamed", ""))))),
       f.status_char()),
    "path\x00" ++ f.display_diff_path(),
  ) ++ "\x1e\n"
).join("")
'''

'log_oneline' = 'log_oneline(self)'
'log_oneline(commit)' = '''
if(commit.root(),
  "root\x00" ++ format_root_commit(commit) ++ "\x1e\n",
  separate("\x00",
    "bijjou_template_name\x00log_oneline",
    "change_id\x00" ++ format_short_change_id_with_change_offset(commit),
    "commit_id\x00" ++ format_short_commit_id(commit.commit_id()),
    "author\x00" ++ format_short_signature_oneline(commit.author()),
    "timestamp\x00" ++ commit_timestamp(commit).format("%y%m%d·%H%M"),
    "labels\x00" ++ format_commit_labels(commit),
    "working_copies\x00" ++ commit.working_copies(),
    "bookmarks\x00" ++ commit.bookmarks(),
    "tags\x00" ++ commit.tags(),
    if(config("ui.show-cryptographic-signatures").as_boolean(),
      "signature\x00" ++ format_short_cryptographic_signature(commit.signature())),
    if(commit.empty(),
      "empty\x00" ++ empty_commit_marker),
    "description\x00" ++ if(commit.description(),
      commit.description().first_line(),
      label("no_desc","no description"),
    ),
  ) ++ "\x1e\n" ++ if(commit.current_working_copy(), diff_numstat(commit)),
)
'''
