'json_colored(value)' = '''
'"' ++ replace(regex:"[\"\\\\\\n]", value, |m|
  if(m.get(0) == "\"", "\\\"",
    if(m.get(0) == "\\", "\\\\",
      "\\n"))) ++ '"'
'''

'my_log_oneline_bijjou(commit)' = '''
if(commit.root(),
  '{"root":' ++ json_colored(format_root_commit(commit)) ++ '}' ++ "\n",
  '{' ++ separate(',',
    '"change_id":' ++ json_colored(format_short_change_id_with_change_offset(commit)),
    '"commit_id":' ++ json_colored(format_short_commit_id(commit.commit_id())),
    '"author":' ++ json_colored(format_short_signature_oneline(commit.author())),
    '"timestamp":' ++ json_colored(commit_timestamp(commit).format("%y%m%d·%H%M")),
    '"labels":' ++ json_colored(format_commit_labels(commit)),
    '"working_copies":' ++ json_colored(commit.working_copies()),
    '"bookmarks":' ++ json_colored(commit.bookmarks()),
    '"tags":' ++ json_colored(commit.tags()),
    if(config("ui.show-cryptographic-signatures").as_boolean(),
      '"signature":' ++ json_colored(format_short_cryptographic_signature(commit.signature()))),
    if(commit.empty(),
      '"empty":' ++ json_colored(empty_commit_marker)),
    '"description":' ++ if(commit.description(),
      json_colored(commit.description().first_line()),
      json_colored(label("no_desc","no description")),
    ),
  ) ++ '}' ++ "\n",
)
'''
